#include "MapData.h"

#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"

DEFINE_LOG_CATEGORY_STATIC(LogMapData, Log, All);

namespace
{

bool ReadJsonArray(const FString& Path, TArray<TSharedPtr<FJsonValue>>& Out, FString& OutError)
{
    FString Text;
    if (!FFileHelper::LoadFileToString(Text, *Path))
    {
        OutError = FString::Printf(TEXT("cannot read %s"), *Path);
        return false;
    }
    const TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(Text);
    if (!FJsonSerializer::Deserialize(Reader, Out))
    {
        OutError = FString::Printf(TEXT("malformed JSON array in %s"), *Path);
        return false;
    }
    return true;
}

bool ReadJsonObject(const FString& Path, TSharedPtr<FJsonObject>& Out, FString& OutError)
{
    FString Text;
    if (!FFileHelper::LoadFileToString(Text, *Path))
    {
        OutError = FString::Printf(TEXT("cannot read %s"), *Path);
        return false;
    }
    const TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(Text);
    if (!FJsonSerializer::Deserialize(Reader, Out) || !Out.IsValid())
    {
        OutError = FString::Printf(TEXT("malformed JSON object in %s"), *Path);
        return false;
    }
    return true;
}

/// `[x, y, z]` -> FVector. The baker already emits Unreal centimetres.
bool ReadPoint(const TSharedPtr<FJsonValue>& Value, FVector& Out)
{
    const TArray<TSharedPtr<FJsonValue>>* Triple = nullptr;
    if (!Value.IsValid() || !Value->TryGetArray(Triple) || Triple->Num() < 3)
    {
        return false;
    }
    Out = FVector((*Triple)[0]->AsNumber(), (*Triple)[1]->AsNumber(), (*Triple)[2]->AsNumber());
    return true;
}

/// A deliberately minimal Wavefront reader: it handles exactly what
/// `bake/src/main.rs` writes (`v`, `vn`, and triangular `f a//a b//b c//c`) and
/// rejects anything else rather than guessing. The file is generated by code in
/// this repo, so the general case is not worth carrying.
bool ParseObj(const FString& Path, TArray<FVector>& OutVerts, TArray<FVector>& OutNormals,
              TArray<int32>& OutIndices, FString& OutError)
{
    TArray<FString> Lines;
    if (!FFileHelper::LoadFileToStringArray(Lines, *Path))
    {
        OutError = FString::Printf(TEXT("cannot read %s"), *Path);
        return false;
    }

    OutVerts.Reset();
    OutNormals.Reset();
    OutIndices.Reset();

    for (const FString& Line : Lines)
    {
        if (Line.StartsWith(TEXT("v ")))
        {
            TArray<FString> Parts;
            Line.ParseIntoArray(Parts, TEXT(" "), true);
            if (Parts.Num() < 4)
            {
                OutError = FString::Printf(TEXT("bad vertex in %s: %s"), *Path, *Line);
                return false;
            }
            OutVerts.Emplace(FCString::Atod(*Parts[1]), FCString::Atod(*Parts[2]),
                             FCString::Atod(*Parts[3]));
        }
        else if (Line.StartsWith(TEXT("vn ")))
        {
            TArray<FString> Parts;
            Line.ParseIntoArray(Parts, TEXT(" "), true);
            if (Parts.Num() < 4)
            {
                OutError = FString::Printf(TEXT("bad normal in %s: %s"), *Path, *Line);
                return false;
            }
            OutNormals.Emplace(FCString::Atod(*Parts[1]), FCString::Atod(*Parts[2]),
                               FCString::Atod(*Parts[3]));
        }
        else if (Line.StartsWith(TEXT("f ")))
        {
            TArray<FString> Parts;
            Line.ParseIntoArray(Parts, TEXT(" "), true);
            if (Parts.Num() != 4)
            {
                OutError = FString::Printf(TEXT("%s has a non-triangular face: %s"), *Path, *Line);
                return false;
            }
            for (int32 i = 1; i <= 3; ++i)
            {
                FString Vertex = Parts[i];
                int32 Slash = INDEX_NONE;
                if (Vertex.FindChar(TEXT('/'), Slash))
                {
                    Vertex.LeftInline(Slash);
                }
                // OBJ indices are 1-based.
                OutIndices.Add(FCString::Atoi(*Vertex) - 1);
            }
        }
    }

    if (OutVerts.Num() == 0 || OutIndices.Num() == 0)
    {
        OutError = FString::Printf(TEXT("%s has no geometry"), *Path);
        return false;
    }
    if (OutNormals.Num() != 0 && OutNormals.Num() != OutVerts.Num())
    {
        // The baker writes one normal per vertex, in step. Anything else means
        // the face indices below would silently pair the wrong two.
        OutError = FString::Printf(TEXT("%s has %d normals for %d vertices"), *Path,
                                   OutNormals.Num(), OutVerts.Num());
        return false;
    }
    return true;
}

} // namespace

bool FMapData::Load(const FString& MapDir, FString& OutError)
{
    if (!ParseObj(FPaths::Combine(MapDir, TEXT("terrain.obj")), TerrainVertices, TerrainNormals,
                  TerrainIndices, OutError))
    {
        return false;
    }

    // --- provinces.json: the sites, the palette, and the bake metadata -----
    {
        TSharedPtr<FJsonObject> Root;
        const FString Path = FPaths::Combine(MapDir, TEXT("provinces.json"));
        if (!ReadJsonObject(Path, Root, OutError))
        {
            return false;
        }

        const TArray<TSharedPtr<FJsonValue>>* Sites = nullptr;
        if (!Root->TryGetArrayField(TEXT("provinces"), Sites))
        {
            OutError = FString::Printf(TEXT("%s has no `provinces` array"), *Path);
            return false;
        }
        for (const TSharedPtr<FJsonValue>& Entry : *Sites)
        {
            const TSharedPtr<FJsonObject> Obj = Entry->AsObject();
            FProvinceSite3D Site;
            Site.Id = Obj->GetIntegerField(TEXT("id"));
            Site.Name = Obj->GetStringField(TEXT("name"));
            const TArray<TSharedPtr<FJsonValue>>& Pos = Obj->GetArrayField(TEXT("pos"));
            // The bake stores XY only; the ground height comes off the terrain
            // mesh at spawn time, so a marker can never float above or sink into
            // a surface that was retuned after the sites were written.
            Site.Position = FVector(Pos[0]->AsNumber(), Pos[1]->AsNumber(), 0.0);
            Provinces.Add(MoveTemp(Site));
        }

        const TArray<TSharedPtr<FJsonValue>>* Colors = nullptr;
        if (Root->TryGetArrayField(TEXT("faction_colors"), Colors))
        {
            for (const TSharedPtr<FJsonValue>& Entry : *Colors)
            {
                const TSharedPtr<FJsonObject> Obj = Entry->AsObject();
                // 0-255 sRGB, as authored in client.yaml.
                const FColor Srgb(static_cast<uint8>(Obj->GetIntegerField(TEXT("r"))),
                                  static_cast<uint8>(Obj->GetIntegerField(TEXT("g"))),
                                  static_cast<uint8>(Obj->GetIntegerField(TEXT("b"))));
                FactionColors.Add(FLinearColor::FromSRGBColor(Srgb));
            }
        }

        const TSharedPtr<FJsonObject>* Extent = nullptr;
        if (Root->TryGetObjectField(TEXT("map_extent"), Extent))
        {
            MapExtent = FVector2D((*Extent)->GetNumberField(TEXT("x")),
                                  (*Extent)->GetNumberField(TEXT("y")));
        }

        const TSharedPtr<FJsonObject>* Meta = nullptr;
        if (Root->TryGetObjectField(TEXT("meta"), Meta))
        {
            (*Meta)->TryGetNumberField(TEXT("world_scale"), WorldScale);
            (*Meta)->TryGetNumberField(TEXT("terrain_exag"), TerrainExag);
        }
    }

    // --- province_borders.json ---------------------------------------------
    {
        TArray<TSharedPtr<FJsonValue>> Entries;
        const FString Path = FPaths::Combine(MapDir, TEXT("province_borders.json"));
        if (!ReadJsonArray(Path, Entries, OutError))
        {
            return false;
        }
        for (const TSharedPtr<FJsonValue>& Entry : Entries)
        {
            const TSharedPtr<FJsonObject> Obj = Entry->AsObject();
            FBorderSegment Segment;
            Segment.A = Obj->GetIntegerField(TEXT("a"));
            Segment.B = Obj->GetIntegerField(TEXT("b"));
            for (const TSharedPtr<FJsonValue>& P : Obj->GetArrayField(TEXT("points")))
            {
                FVector Point;
                if (!ReadPoint(P, Point))
                {
                    OutError = FString::Printf(TEXT("bad border point in %s"), *Path);
                    return false;
                }
                Segment.Points.Add(Point);
            }
            Borders.Add(MoveTemp(Segment));
        }
    }

    // --- rivers.json --------------------------------------------------------
    {
        TArray<TSharedPtr<FJsonValue>> Entries;
        const FString Path = FPaths::Combine(MapDir, TEXT("rivers.json"));
        if (!ReadJsonArray(Path, Entries, OutError))
        {
            return false;
        }
        for (const TSharedPtr<FJsonValue>& Entry : Entries)
        {
            const TSharedPtr<FJsonObject> Obj = Entry->AsObject();
            FRiverPolyline River;
            River.Width = Obj->GetNumberField(TEXT("width"));
            for (const TSharedPtr<FJsonValue>& P : Obj->GetArrayField(TEXT("points")))
            {
                FVector Point;
                if (!ReadPoint(P, Point))
                {
                    OutError = FString::Printf(TEXT("bad river point in %s"), *Path);
                    return false;
                }
                River.Points.Add(Point);
            }
            Rivers.Add(MoveTemp(River));
        }
    }

    // --- forests.json -------------------------------------------------------
    {
        TArray<TSharedPtr<FJsonValue>> Entries;
        const FString Path = FPaths::Combine(MapDir, TEXT("forests.json"));
        if (!ReadJsonArray(Path, Entries, OutError))
        {
            return false;
        }
        for (const TSharedPtr<FJsonValue>& Entry : Entries)
        {
            const TSharedPtr<FJsonObject> Obj = Entry->AsObject();
            FForestInstance Tree;
            if (!ReadPoint(Obj->TryGetField(TEXT("pos")), Tree.Position))
            {
                OutError = FString::Printf(TEXT("bad forest position in %s"), *Path);
                return false;
            }
            Tree.Scale = Obj->GetNumberField(TEXT("scale"));
            Tree.YawDegrees = Obj->GetNumberField(TEXT("yaw_deg"));
            Forests.Add(Tree);
        }
    }

    UE_LOG(LogMapData, Log,
           TEXT("baked map: %d verts, %d borders, %d rivers, %d trees, %d provinces"),
           TerrainVertices.Num(), Borders.Num(), Rivers.Num(), Forests.Num(), Provinces.Num());
    return true;
}

FLinearColor FMapData::ColorFor(int32 Faction) const
{
    if (!FactionColors.IsValidIndex(Faction))
    {
        return FLinearColor(0.45f, 0.42f, 0.38f);
    }
    return FactionColors[Faction];
}

FVector FMapData::SiteOf(int32 Province) const
{
    for (const FProvinceSite3D& Site : Provinces)
    {
        if (Site.Id == Province)
        {
            return Site.Position;
        }
    }
    return FVector::ZeroVector;
}
